### ISSUE TITLE
Instructions to Create a Hackintosh on the Surface Book 1

### ISSUE THREAD

**Issue by alee-bee** [baumph/Surface-Book-1-Hackintosh#1]
So with the files you provided in the repository are we supposed to use Rufus or Etcher to create a bootable usb then just boot the Surface Book with it? There are 2 folders and I want to download MacOS on my surface book badly.

**Comment by baumph** [comment]
Follow this tutorial to do it on a Windows machine. It is easier with a Mac though. 
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos

**Comment by alee-bee** [comment]
> 
> 
> Follow this tutorial to do it on a Windows machine. It is easier with a Mac though.
> https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos

Thanks for the reply, I'm currently following the guide and just wanted to know which EFI folder to use from your repository?

**Comment by baumph** [comment]
You can use either of them. But I would recommend the OC 0.6.6 version. It has a newer OpenCore version and should work perfect with BugSur

**Comment by jmacie** [comment]
I have a surface book 1. I had Sierra with a clover efi and windows dual boot. I lost the efi with a windows upgrade and even though I had a backup I couldn't get OS X back booting. I discovered you have an open core efi and are booting bigsur. I made a bootable Big Sur install stick and tried both your efi s, but neither would boot. They stopped right away without any verbose at all. Have any ideas? I have such a hard time with open core and dortania. If you have any pointers, I do have other hackintoshes that I have done opencore efis from scratch I just wish I could use yours, since you worked so hard and are generous to put it out here. Any info appreciated, Johnm
